# Generated by Django 4.0.1 on 2022-06-24 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_action_act_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 16, 29, 22, 212233, tzinfo=utc), verbose_name='action date'),
        ),
    ]
