# Generated by Django 4.0.1 on 2022-01-30 15:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_action_act_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 15, 9, 26, 948227, tzinfo=utc), verbose_name='action date'),
        ),
    ]
