# Generated by Django 4.0.1 on 2022-02-08 17:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_action_act_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photo_de_profile')),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='user',
        ),
        migrations.AddField(
            model_name='action',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 8, 17, 49, 16, 852654, tzinfo=utc), verbose_name='action date'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='action',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
    ]
