# Generated by Django 4.0.1 on 2022-08-30 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_action_act_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='act_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='action date'),
        ),
    ]
