# Generated by Django 4.0.1 on 2022-02-08 21:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_action_act_date_alter_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 8, 21, 8, 20, 671980, tzinfo=utc), verbose_name='action date'),
        ),
        migrations.AlterField(
            model_name='player',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo_de_profile'),
        ),
    ]
