# Generated by Django 4.0.1 on 2022-12-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_mise_misejoueur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('cote', models.FloatField()),
                ('reussi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PariJoueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mise', models.IntegerField()),
                ('pari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.pari')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
    ]
