# Generated by Django 4.0.1 on 2022-01-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='points',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nom',
            new_name='name',
        ),
    ]
