# Generated by Django 4.0.1 on 2022-01-30 08:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_points_action_point_rename_nom_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='act_date',
            field=models.TimeField(default=datetime.datetime(2022, 1, 30, 8, 40, 48, 684601, tzinfo=utc), verbose_name='action date'),
        ),
    ]
