# Generated by Django 4.0.1 on 2022-01-30 08:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_action_act_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='act_date',
            field=models.TimeField(default=datetime.datetime(2022, 1, 30, 8, 50, 52, 214330, tzinfo=utc), verbose_name='action date'),
        ),
    ]
