# Generated by Django 4.0.1 on 2022-02-08 18:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_action_act_date_alter_action_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='act_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 8, 18, 1, 41, 933335, tzinfo=utc), verbose_name='action date'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo_de_profile'),
        ),
    ]
